client/src/models/bar.js
client/src/models/specs/bar_spec.js
package.json

adds bar.js and matching spec file with passing tests

---

package-lock.json
seeds.js

adds Gin71 M City

---

seeds.js

Hey there - can you have a gander at this please? Thanks!

spiritualist gin added to seeds

---

seeds.js

adds Gin71 Glasgow to seeds.js

---

seeds.js

new bar added - can you take a look - thanks!

slouch bar added to database

---

seeds.js

adds Finnieston to seeds.js

---

seeds.js

can you take a look please? thanks!

alston grill added

---

client/build/index.html

adds basic index.html and main.css

---

client/build/main.css

basic css structure

---

seeds.js

adds beGin to seeds.js

---

client/build/main.css
client/src/app.js
client/src/models/mapWrapper.js

Resolves #8 
Adds search bar to the map. When the user selects a place from the search results the map centers on the chosen place and puts a marker down.

adds search bar and chosen place marker

---

client/build/index.html
client/src/app.js
client/src/models/mapWrapper.js

resolves #29
Hi there,
So the functionality works ok - have added a temporary button just to show that - but let me know if you can think of a better way to do it!
We can then discuss tomorrow if we want it just to be a one-off undo option (which currently works) or whether we want to be more specific.
We also need to decide how it's triggered....
Have duplicated the add marker function as the easiest way to differentiate between the two types of marker = prepopulated or user-added,  as they end up in different arrays in the constructor.

Adds tester button and function to remove markers added by search

---

client/src/app.js
client/src/models/mapWrapper.js

Resolves #13 
A marker is created for each Bar within the API data. An infoWindow is created for each marker with associated content (bar name, open time and closed time).

populates map with bar markers with associated infoWindows

---

client/src/models/mapWrapper.js

This uses a built-in feature .repeat() - works with unicode. Not sure if it's supported by older browsers but what do you reckon?

adds stars to info window

---

client/build/index.html
client/build/launch.css
client/build/main.css
client/src/app.js

Not ready to commit - but have sorted out the map issue. we just need to delay the z-index change until the transition has completed. setTimeOut(function, #ofmilliseconds) might work?

alter z-index so map is clickable

---

client/src/models/mapWrapper.js

Changes info window text from open / closed to opens / closes.

amends info window open/closed text

---

client/src/models/mapWrapper.js

Partial resolution to issue 30. 
Uses user location as start point (point A) .
Next part of resolution will use the list on click event to set the end point (point B) as the bar which has been clicked.

adds direction from geolocation

---

client/src/app.js
client/src/models/mapWrapper.js

Adds the Bar location as the directions end point but there is an issue with when the onClick is triggered. The list must be clicked twice for the onClick to fire.

adds directions from geolocation to a clicked bar - issue with onclick

---

client/src/models/mapWrapper.js

Keeps map type consistency by removing the change to hybrid.

removes map type change to hybrid in centerFunction

---

client/src/app.js
client/src/models/mapWrapper.js

fixes direction double-click to show directions on single click

---

client/src/app.js

Adds the bracket to app.js which was chopped in the last merge

adds missing bracket to app.js

---

client/build/index.html
client/build/main.css
client/src/app.js

Hi guys. Can't seem to get the button to move right in that div.... Please let me know if you figure it out :)

Moves dropdown button

---

client/build/launch.css

amends padding in launch message to fix orphan

---

seeds.js

adds test distillery to seeds.js

---

client/build/main.css
client/src/app.js

Shows distilleries only, on click of dropdown option

Shows list of distilleries

---

client/build/main.css

Added the search bar to CSS so it can be styled further if required

moves searchbar from top of map

---

client/src/app.js

Hi guys - this is the function that will rank whatever we pass into it by size high to low.....How we do that and where we trigger it is up for debate but it'd be good to get it into the code base :)

Adds sort by rating high-to-low function with bubble sort, currently just for Glasgow

---

client/build/main.css
client/src/app.js

The styling is quite fidgety so laid it out as clearly as I could for now, can always give it a polish tomorrow. Variable names subject to change in my next update, doing that in one big batch.

adds the top 3 gins for each bar and some styling

---

client/src/app.js

just deleted that space - saw it when I went in to app.js. looks fab!

amends concatentation of createTopGins

---

client/build/main.css
client/src/app.js

Fixes decimal places on prices

---

client/build/index.html
client/build/main.css
client/src/app.js
client/src/models/mapWrapper.js
seeds.js

Updates app.js as well as the html and css files to make functions more readable for use with bars and distilleries.  Also removed a comma from the end of the distilleries collection

updates variable names to include various venues

---

client/build/main.css

amends font and colour of You are here

---

client/build/main.css

Adjusts dropdown item width

---

seeds.js

edits to coords on seeds.js

---

seeds.js

shortens juniper gin bar address

---

client/src/app.js

Resolves #72 
Also opens one panel at a time

amends list to open hidden panels one at a time

---

client/build/index.html
client/src/app.js

fixes list item click issue

---

seeds.js

corrects typo in seeds.js

---

client/src/app.js

Abstracted out the function to wipe the welcome message on any click and implemented it for dropdown options as well as list items. Also refactored the sort functions to include the image creator

now works when selecting dropdown option

---

client/src/app.js

adds scroll to list top when Sort By option is selected
